# Generated manually for portable scaffold
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import clubs.models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Club', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=160, unique=True)), ('description', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True))], options={'ordering': ['name']}),
        migrations.CreateModel(name='EventCategory', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=80, unique=True)), ('color', models.CharField(default='#0d6efd', max_length=24))], options={'verbose_name_plural': 'event categories', 'ordering': ['name']}),
        migrations.CreateModel(name='EventTag', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=60, unique=True))], options={'ordering': ['name']}),
        migrations.CreateModel(name='Profile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ClubLeadership', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('assigned_at', models.DateTimeField(auto_now_add=True)), ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='clubs.club')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_leaderships', to=settings.AUTH_USER_MODEL))], options={'ordering': ['club__name', 'user__last_name'], 'unique_together': {('club', 'user')}}),
        migrations.CreateModel(name='ClubMembership', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('joined_at', models.DateTimeField(auto_now_add=True)), ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL))], options={'ordering': ['club__name', 'user__last_name', 'user__first_name'], 'unique_together': {('club', 'user')}}),
        migrations.CreateModel(name='Event', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=180)), ('description', models.TextField(blank=True)), ('event_date', models.DateTimeField()), ('location', models.CharField(blank=True, max_length=220)), ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/')), ('capacity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited capacity.', null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clubs.eventcategory')), ('clubs', models.ManyToManyField(related_name='events', to='clubs.club')), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)), ('tags', models.ManyToManyField(blank=True, related_name='events', to='clubs.eventtag'))], options={'ordering': ['event_date', 'title']}),
        migrations.CreateModel(name='EventRSVP', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('status', models.CharField(choices=[('going', 'Going'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='going', max_length=16)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='clubs.event')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL))], options={'ordering': ['event__event_date', 'created_at'], 'unique_together': {('event', 'user')}}),
        migrations.CreateModel(name='Attendance', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('checked_in_at', models.DateTimeField(auto_now_add=True)), ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_checked', to=settings.AUTH_USER_MODEL)), ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='clubs.event')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-checked_in_at'], 'unique_together': {('event', 'user')}}),
        migrations.AddField(model_name='club', name='members', field=models.ManyToManyField(related_name='clubs', through='clubs.ClubMembership', to=settings.AUTH_USER_MODEL)),
    ]
